const COUNTRY_CURRENCY = {
  "India": { symbol: "₹", code: "INR" },
  "United States": { symbol: "$", code: "USD" },
  "United Kingdom": { symbol: "£", code: "GBP" },
  "Germany": { symbol: "€", code: "EUR" },
  "France": { symbol: "€", code: "EUR" },
  "Italy": { symbol: "€", code: "EUR" },
  "Spain": { symbol: "€", code: "EUR" },
  "Netherlands": { symbol: "€", code: "EUR" },
  "Portugal": { symbol: "€", code: "EUR" },
  "Belgium": { symbol: "€", code: "EUR" },
  "Austria": { symbol: "€", code: "EUR" },
  "Ireland": { symbol: "€", code: "EUR" },
  "Greece": { symbol: "€", code: "EUR" },
  "Finland": { symbol: "€", code: "EUR" },
  "Japan": { symbol: "¥", code: "JPY" },
  "China": { symbol: "¥", code: "CNY" },
  "South Korea": { symbol: "₩", code: "KRW" },
  "Australia": { symbol: "A$", code: "AUD" },
  "Canada": { symbol: "C$", code: "CAD" },
  "New Zealand": { symbol: "NZ$", code: "NZD" },
  "Switzerland": { symbol: "CHF", code: "CHF" },
  "Sweden": { symbol: "kr", code: "SEK" },
  "Norway": { symbol: "kr", code: "NOK" },
  "Denmark": { symbol: "kr", code: "DKK" },
  "Brazil": { symbol: "R$", code: "BRL" },
  "Mexico": { symbol: "MX$", code: "MXN" },
  "Singapore": { symbol: "S$", code: "SGD" },
  "United Arab Emirates": { symbol: "AED", code: "AED" },
  "Saudi Arabia": { symbol: "SAR", code: "SAR" },
  "South Africa": { symbol: "R", code: "ZAR" },
  "Nigeria": { symbol: "₦", code: "NGN" },
  "Kenya": { symbol: "KSh", code: "KES" },
  "Pakistan": { symbol: "₨", code: "PKR" },
  "Bangladesh": { symbol: "৳", code: "BDT" },
  "Sri Lanka": { symbol: "Rs", code: "LKR" },
  "Thailand": { symbol: "฿", code: "THB" },
  "Indonesia": { symbol: "Rp", code: "IDR" },
  "Malaysia": { symbol: "RM", code: "MYR" },
  "Philippines": { symbol: "₱", code: "PHP" },
  "Vietnam": { symbol: "₫", code: "VND" },
  "Russia": { symbol: "₽", code: "RUB" },
  "Turkey": { symbol: "₺", code: "TRY" },
  "Argentina": { symbol: "AR$", code: "ARS" },
};

const getCurrency = (country) =>
  COUNTRY_CURRENCY[country] || { symbol: "$", code: "USD" };

module.exports = { getCurrency };